[[main]]
none = "none"

[[main]]
name = "Tech"
pageRef = "posts"
identifier = "aAy79r74Az"
weight = 9992

[[main]]
name = "About"
pageRef = "about"
identifier = "iBnSg774Tv"
weight = 9991

[[main]]
name = "Tags"
pageRef = "tags"
identifier = "LoLI6MLuqf"
weight = 9994

[[main]]
name = "Coffee Reads"
pageRef = "reads"
identifier = "3TaCHTMxvz"
weight = 9993

[[footer]]
none = "none"
