colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
disableImageOptimization = false
disableTextInHeader = false
highlightCurrentMenuArea = "highlightCurrentMenuArea"
smartTOC = true
smartTOCHideUnfocusedChildren = ""
defaultBackgroundImage = "image.jpg"
defaultFeaturedImage = ""

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
homepageImage = "image.jpg"
showRecent = true
showRecentItems = 3
showMoreLink = false
showMoreLinkDest = "/posts"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = true

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = "showTableOfContents"
showTaxonomies = true
showAuthorsBadges = ""
showWordCount = false
showZenMode = "showZenMode"
showRelatedContent = false
showComments = true
sharingLinks = [ "linkedin", "twitter", "reddit", "facebook", "email"]

[list]
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = "showSummary"
showViews = false
showLikes = false
showTableOfContents = "showTableOfContents"
showCards = false
orderByWeight = false
groupByYear = true
cardView = false
cardViewScreenWidth = ""
constrainItemsWidth = ""
heroStyle = "background"

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = "cardView"

[term]
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = "cardView"
cardViewScreenWidth = false

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[buymeacoffee]

[verification]
