baseURL = 'https://ana-cozma.github.io/blog'
languageCode = 'en-us'
title = 'Tech and Tea: Navigating the World of Technology'
theme = 'm10c'

[params]
  author = "Ana Cozma"
  description = "A blog about navigating the world of technology."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/ana-cozma"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/the_cozma"
