baseURL = "https://ana-cozma.github.io/blog"
languageCode = "en-us"
title = "Ana Cozma's Blog"
theme = "m10c"
avatar = 'static/images/avatar/avatar.png'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tech"
    name = "Tech"
    url = "/tech/"
    weight = 2
  [[menu.main]]
    identifier = "tea"
    name = "Tea"
    url = "/tea/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

[params]
  author = "Ana Cozma"
  description = "Tech and Tea: Navigating the World of Technology"
  menu_item_separator = " | "

  [params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightColor = "#afbac4"
    lightestColor = "#ffffff"
    ##primaryColor = "#8f60cc"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/ana-cozma"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/the_cozma"
